---
conditions: v1

stages:
  - name: test
  - name: deploy
    if: tag IS present

sudo: required
dist: xenial
language: python

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/

cache: pip
jobs:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=linting TOXCFG=tox.ini
      stage: test

    - python: 3.8
      env: TOXENV=py38 TOXCFG=tox.ini
      stage: test

    - python: 3.7
      env: TOXENV=py37 TOXCFG=tox.ini
      stage: test

    - python: 3.6
      env: TOXENV=py36 TOXCFG=tox.ini
      stage: test

    - stage: deploy
      python: 3.7
      install:
        - sudo apt-get update
        - sudo apt-get -y install nsis
        - pip install pynsist tabulate jsondiff openpyxl>=2.6.0
      script: pynsist installer.cfg
      deploy:
        provider: releases
        api_key: ${GITHUB_DEPLOY_TOKEN}
        file: build/nsis/elisctl_rossum_3.13.0.exe
        skip_cleanup: true
        on:
          tags: true

    - stage: deploy
      script: skip
      python: 3.7
      deploy:
        provider: pypi
        edge: true
        username: "__token__"
        password: ${PYPI_DEPLOY_TOKEN}
        on:
          tags: true


install:
  - pip install tox-travis setuptools --upgrade

# command to run tests
script:
  - tox -c ${TOXCFG}


